[package]
name = "reth-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-network-types = { workspace = true, features = ["serde"] }
reth-prune-types.workspace = true
reth-stages-types.workspace = true
reth-primitives = { workspace = true, optional = true }

# serde
serde.workspace = true
humantime-serde.workspace = true

# toml
confy.workspace = true

[dev-dependencies]
tempfile.workspace = true
toml.workspace = true
reth-network-peers.workspace = true

[features]
bsc = [
    "reth-primitives/bsc"
]