# Runs unit tests.

name: unit

on:
  pull_request:
    branches: [ main, develop ]
  merge_group:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust
  TOOL_CHAIN: "1.80"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test / ${{ matrix.network }} (${{ matrix.partition }}/3)
    runs-on: [ bnb-chain-ap-qa-cicd-runners ]
    env:
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        partition: [ 1, 2, 3 ]
        network: [ ethereum, optimism, bsc ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOL_CHAIN }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest
      - if: matrix.network == 'ethereum'
        name: Run tests
        run: |
          cargo nextest run \
            --locked --features "asm-keccak ${{ matrix.network }}" \
            --workspace --exclude ef-tests \
            --partition hash:${{ matrix.partition }}/3 \
            -E "!kind(test)"
      - if: matrix.network == 'optimism'
        name: Run tests
        run: |
          cargo nextest run \
            --locked --features "asm-keccak ${{ matrix.network }} opbnb" \
            --workspace --exclude ef-tests --exclude reth-node-ethereum \
            --partition hash:${{ matrix.partition }}/3 \
            -E "!kind(test)"
      - if: matrix.network == 'bsc'
        name: Run tests
        run: |
          cargo nextest run \
            --locked --features "asm-keccak ${{ matrix.network }}" \
            --workspace --exclude examples --exclude example-exex-rollup --exclude ef-tests --exclude reth-beacon-consensus \
            --exclude reth-blockchain-tree --exclude reth-node-ethereum --exclude reth-rpc-engine-api \
            --partition hash:${{ matrix.partition }}/3 \
            -E "!kind(test)"

  state:
    name: Ethereum state tests
    runs-on: [ bnb-chain-ap-qa-cicd-runners ]
    env:
      RUST_LOG: info,sync=error
      RUST_BACKTRACE: 1
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Checkout ethereum/tests
        uses: actions/checkout@v4
        with:
          repository: ethereum/tests
          ref: 1c23e3c27ac53b794de0844d2d5e19cd2495b9d8
          path: testing/ef-tests/ethereum-tests
          submodules: recursive
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOL_CHAIN }}
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo nextest run --release -p ef-tests --features "asm-keccak ef-tests"

  doc:
    name: doc tests (${{ matrix.network }})
    runs-on: [ bnb-chain-ap-qa-cicd-runners ]
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - network: ethereum
            extra-features: ""
          - network: optimism
            extra-features: "opbnb"
          - network: bsc
            extra-features: ""
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOL_CHAIN }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run doctests
        run: cargo test --doc --workspace --features "${{ matrix.network }} ${{ matrix.extra-features }}"

  unit-success:
    name: unit success
    runs-on: ubuntu-latest
    if: always()
    needs: [ test, state, doc ]
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
